In [17]:
import torch
import matplotlib.pyplot as plt
def box_iou(boxes1,boxes2):

    """计算两个锚框或边界框列表中成对的交并比"""
    # 定义一个lambda函数，计算一个锚框或边界框的面积
    box_area = lambda boxes: ((boxes[:,2] - boxes[:,0]) *
                             (boxes[:,3] - boxes[:,1]))
    # 计算boxes1中每个框的面积
    areas1 = box_area(boxes1) 
    # 计算boxes2中每个框的面积
    areas2 = box_area(boxes2) 
    # 计算交集区域的左上角坐标（对于每对框，取其左上角坐标的最大值）
    inter_upperlefts = torch.max(boxes1[:,None,:2],boxes2[:,:2])
    print(f"shape1:{inter_upperlefts.shape}")
    # 计算交集区域的右下角坐标（对于每对框，取其右下角坐标的最小值）
    inter_lowerrights = torch.min(boxes1[:,None,2:],boxes2[:,2:])
    # 计算交集区域的宽和高（如果交集不存在，宽和高为0）
    inters = (inter_lowerrights - inter_upperlefts).clamp(min=0)
    print(f"shape2:{inters.shape}")
    # 计算交集区域的面积
    inter_areas = inters[:,:,0] * inters[:,:,1]
    print('----------')
    print(inters.shape)
    print(inters)
    print('----------')
    print(inters[:,:,0].shape)
    print(inters[:,:,0])
    print('----------')
    print(inters[:,:,1].shape)
    print(inters[:,:,1])
    # 计算并集区域的面积（boxes1的面积 + boxes2的面积 - 交集的面积）
    union_areas = areas1[:,None] + areas2 - inter_areas 
    # 返回交并比（交集的面积除以并集的面积）
    return inter_areas / union_areas
boxes1 = torch.tensor([
    [10, 20, 50, 60],   # 框1
    [0, 0, 100, 100]    # 框2
])

# boxes2 有 3 个框
boxes2 = torch.tensor([
    [15, 25, 55, 65],   # 框A
    [5, 5, 95, 95],     # 框B
    [30, 30, 70, 70]    # 框C
])
zz = box_iou(boxes1,boxes2)

shape1:torch.Size([2, 3, 2])
shape2:torch.Size([2, 3, 2])
----------
torch.Size([2, 3, 2])
tensor([[[35, 35],
         [40, 40],
         [20, 30]],

        [[40, 40],
         [90, 90],
         [40, 40]]])
----------
torch.Size([2, 3])
tensor([[35, 40, 20],
        [40, 90, 40]])
----------
torch.Size([2, 3])
tensor([[35, 40, 30],
        [40, 90, 40]])
