In [1]:
import torch
import matplotlib.pyplot as plt
data = plt.imread('img/catdog.jpg')
in_height, in_width = data.shape[-2:]
sizes = [0.75,0.5,0.25]
ratios = [1,2,0.5]
size_tensor = torch.tensor(sizes)
ratio_tensor = torch.tensor(ratios)
x = torch.tensor([0, 1])
y = torch.tensor([2, 3, 4])
xx,yy = torch.meshgrid(x,y,indexing='ij')
xx, yy = xx.reshape(-1), yy.reshape(-1)
w = torch.cat((size_tensor * torch.sqrt(ratio_tensor[0]),sizes[0] * torch.sqrt(ratio_tensor[1:]))) * in_height / in_width
h = torch.cat((size_tensor / torch.sqrt(ratio_tensor[0]),sizes[0] / torch.sqrt(ratio_tensor[1:])))
anchor_manipulations = torch.stack((-w, -h, w, h)).T.repeat(2, 1)
print(w.shape)
print(h.shape)
print(anchor_manipulations.shape)
print(anchor_manipulations)


torch.Size([5])
torch.Size([5])
torch.Size([10, 4])
tensor([[-1.8200e+02, -7.5000e-01,  1.8200e+02,  7.5000e-01],
        [-1.2133e+02, -5.0000e-01,  1.2133e+02,  5.0000e-01],
        [-6.0667e+01, -2.5000e-01,  6.0667e+01,  2.5000e-01],
        [-2.5739e+02, -5.3033e-01,  2.5739e+02,  5.3033e-01],
        [-1.2869e+02, -1.0607e+00,  1.2869e+02,  1.0607e+00],
        [-1.8200e+02, -7.5000e-01,  1.8200e+02,  7.5000e-01],
        [-1.2133e+02, -5.0000e-01,  1.2133e+02,  5.0000e-01],
        [-6.0667e+01, -2.5000e-01,  6.0667e+01,  2.5000e-01],
        [-2.5739e+02, -5.3033e-01,  2.5739e+02,  5.3033e-01],
        [-1.2869e+02, -1.0607e+00,  1.2869e+02,  1.0607e+00]])


In [8]:
v1 = torch.tensor([[1,2],[3,4]])
v2 = torch.tensor([[5,6],[7,8]])
v3 = v1.repeat_interleave(2,dim=)
print(v1.shape)
print(v3.shape)
print(v3)

torch.Size([2, 2])
torch.Size([2, 4])
tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


In [15]:
x = torch.tensor([[1,2],[3,4]])
y = x.repeat_interleave(2,dim=1)
print(x.shape)
print(x)
print(y.shape)
print(y)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 4])
tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])
