In [1]:
import torch

In [2]:
x = torch.Tensor([[1,2,3],[6,6,6]])
print(x.shape)
x=x.sum(dim=0)
print(x.shape)
print(x)

torch.Size([2, 3])
torch.Size([3])
tensor([7., 8., 9.])


In [3]:
x = torch.Tensor([[[[0,0,0],[1,1,1]],[[2,2,2],[3,3,3]]],[[[4,4,4],[5,5,5]],[[6,6,6],[7,7,7]]]])
print(x.shape)
keepdim_x = x.sum(dim=(0,2,3),keepdim=True)
print('keep_dim_shape:',keepdim_x.shape)
x=x.sum(dim=(0,2,3))
print(x.shape)
print(x)

torch.Size([2, 2, 2, 3])
keep_dim_shape: torch.Size([1, 2, 1, 1])
torch.Size([2])
tensor([30., 54.])


In [10]:
x = torch.Tensor([[0,0,0],[1,2,3]])
print('------x')
print(x)
print('------mean')
mean = x.mean(dim=0)
print(mean.shape)
print(mean)
print('------var')
var = (x - mean)
print(var.shape)
print(var)

print('----------')
v1 = torch.Tensor([[[0,0,0],[1,2,3]],[[0,0,0],[1,2,3]]])
v2 = torch.Tensor([[0,0,0],[1,2,3]])
print(v1.shape)
print(v2.shape)
print(v1+v2)

------x
tensor([[0., 0., 0.],
        [1., 2., 3.]])
------mean
torch.Size([3])
tensor([0.5000, 1.0000, 1.5000])
------var
torch.Size([2, 3])
tensor([[-0.5000, -1.0000, -1.5000],
        [ 0.5000,  1.0000,  1.5000]])
----------
torch.Size([2, 2, 3])
torch.Size([2, 3])
tensor([[[0., 0., 0.],
         [2., 4., 6.]],

        [[0., 0., 0.],
         [2., 4., 6.]]])
