In [71]:
import torch
X = torch.normal(0,1,(1,2),requires_grad = True)
w = torch.tensor([2,-3.4])
w *= 2
b = 4.2
y = torch.matmul(X,w) + b
y.sum().backward()
print(X)
print(y)
print(X.grad)

tensor([[1.2166, 1.2164]], requires_grad=True)
tensor([0.7953], grad_fn=<AddBackward0>)
tensor([[ 4.0000, -6.8000]])
None
