In [1]:
import torch
from matplotlib import pyplot as plt
def bbox_to_rect(bbox, color):
    """Defined in :numref:`sec_bbox`"""
    # 将边界框(左上x,左上y,右下x,右下y)格式转换成matplotlib格式：
    # ((左上x,左上y),宽,高)
    return plt.Rectangle(
        xy=(bbox[0], bbox[1]), width=bbox[2]-bbox[0], height=bbox[3]-bbox[1],
        fill=False, edgecolor=color, linewidth=2)

In [56]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([6,7,8])
v3 = torch.tensor([5])
x_value,y_value = torch.meshgrid(v1, v2,indexing='ij')
new_x_value = x_value.reshape(-1)
print(x_value.shape)
print(x_value)
print(new_x_value.shape)
print(new_x_value)
cat = torch.cat((v1,v2))
print(cat)
v4 = v3.repeat(3,4,5)
print(v4.shape)
print(v4)

torch.Size([3, 3])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
torch.Size([9])
tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])
tensor([1, 2, 3, 6, 7, 8])
torch.Size([3, 4, 5])
tensor([[[5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5]],

        [[5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5]],

        [[5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5]]])
